/**
 * Shinobi Launcher — main.js (thin bootstrap)
 *
 * MAIN ORCHESTRATOR
 *
 *   Multi-region (BR/NA/EU/HK/DE/ES/PL/FR) with per-profile language (pt/en/de/es/pl/fr).
 *   Encrypted backup AES-256-GCM + PBKDF2 with master password.
 *   No tracking — local logs on disk.
 *   Diagnostics exporter in Settings → Advanced (explicit opt-in).
 *
 * BOOT ORDER (CRITICAL):
 *   1. [top-level, before ready] loadConfig (sync) + findFlashPlugin
 *   2. [top-level, before ready] main/flags.applyAll() ← ONLY place that touches commandLine
 *   3. [ready] subsystems: store.load, guard.start, eventTimers.startWithProfiles
 *   4. [ready] ui/controller.createManagerWindow()
 *
 * ARCHITECTURE:
 *   Electron 11.5.0 (LAST with PPAPI Flash) + Clean Flash 34.0 bundled.
 *   UI in vanilla JS/HTML/CSS (zero framework inside Electron) = ~45MB RAM idle.
 *   Tauri does NOT run Flash (WebView2/WebKitGTK removed PPAPI since Chrome 88).
 */

'use strict';

// ── MESA env migration (before anything else) ──
// MESA_GLSL_CACHE_DISABLE was renamed to MESA_SHADER_CACHE_DISABLE in
// recent Mesa versions and emits a deprecation warning every boot.
// We silently migrate preserving the user's intent (if they set
// the old name in the shell). vblank_mode is intentional (user vsync) —
// we don't touch it.
(function _migrateMesaEnv() {
  if (
    process.env.MESA_GLSL_CACHE_DISABLE !== undefined &&
    process.env.MESA_SHADER_CACHE_DISABLE === undefined
  ) {
    process.env.MESA_SHADER_CACHE_DISABLE = process.env.MESA_GLSL_CACHE_DISABLE;
  }
  delete process.env.MESA_GLSL_CACHE_DISABLE;
})();

// NOTE — Fontconfig warnings ("invalid attribute 'xsi:nil'" /
// "invalid constant used"): are host system noise, not from the launcher.
// Come from /etc/fonts/conf.d/48-guessfamily.conf (invalid XML generated by a
// schema-aware tool on some distros). The AppImage can't
// fix /etc/fonts — these warnings are harmless (fonts continue
// working) and don't affect the game. To silence permanently, the
// user can remove/repair that system file.

const { app, dialog, ipcMain } = require('electron');
const path = require('path');

// ═══════════════════════════════════════════════════════════════════════════
// BOOT PHASE 1 — BEFORE app.ready (flags MUST be applied here)
// ═══════════════════════════════════════════════════════════════════════════

const logger = require('./utils/logger');

const { loadConfig } = require('./config/settings');
const { findFlashPlugin, getFlashVersion } = require('./flash/plugin');
const flags = require('./main/flags');

// Config sync (app.getPath('userData') is valid before ready)
let config = loadConfig();

// Flash detection (path + version only — flags.js handles the rest)
const flashPath = findFlashPlugin();
const flashVersion = flashPath ? getFlashVersion(path.dirname(flashPath)) : null;

// ══ APPLY GPU ENV VARS BEFORE READY ══
// GpuDetector.getEnvVars() returns GPU-specific env vars
// (NVIDIA __GL_*, AMD RADEONSI_ZERO_VRAM, Intel INTEL_DEBUG, MALLOC_ARENA_MAX, etc.)
// GPU env vars must be set BEFORE app.whenReady() so the GPU process inherits them.
const gpuDetector = require('./app/GpuDetector');
const gpuEnvVars = gpuDetector.getEnvVars(config.optimizationPreset || 'balanced');
for (var _envKey in gpuEnvVars) {
  if (Object.prototype.hasOwnProperty.call(gpuEnvVars, _envKey)) {
    process.env[_envKey] = gpuEnvVars[_envKey];
  }
}
if (Object.keys(gpuEnvVars).length > 0) {
  logger.info('GPU env vars applied: ' + Object.keys(gpuEnvVars).join(', '));
}

// ══ APPLY ALL FLAGS BEFORE READY ══
// (main/flags.js is the ONLY authority over commandLine.appendSwitch)
flags.applyAll({
  flashPath: flashPath,
  flashVersion: flashVersion,
  hardwareProfile: config.hardwareProfile,
  forceLowSpec: config.forceLowSpec === true,
  optimizationPreset: config.optimizationPreset
});

// Single Instance Lock
const gotTheLock = app.requestSingleInstanceLock();
if (!gotTheLock) {
  app.quit();
}

// ═══════════════════════════════════════════════════════════════════════════
// SUBSYSTEMS (lazy require to avoid circular deps)
// ═══════════════════════════════════════════════════════════════════════════

const memoryGuard = require('./memory/guard');
const eventTimers = require('./utils/EventTimers');
const profileStore = require('./profiles/store');
const profileManager = require('./profiles/manager');
const partition = require('./profiles/partition');
const vault = require('./profiles/vault');
const i18n = require('./config/i18n');

let uiManager = null;
let setupWindow = null;
let isQuitting = false;
let activeGameWindows = 0;

// Applies config language to global i18n
i18n.setLanguage(config.language || 'pt');

// Applies Light Mode (renamed from LowSpec — legacy config backward-compat)
if (config.forceLowSpec !== undefined) {
  memoryGuard.setForceLowSpec(config.forceLowSpec === true);
}
partition.setLowSpecMode(memoryGuard.isLowSpecMode());
if (config.mutedEvents) eventTimers.setMuted(true);

// ═══════════════════════════════════════════════════════════════════════════
// GAME LAUNCH — no tray (user request: "don't want it in the tray")
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Launches the game for a profile DELEGATING to ProfileManager (facade).
 *
 * MULTI-ACCOUNT: the manager STAYS VISIBLE when a game opens, so
 * the user can Play other accounts simultaneously (each profile
 * already runs in an isolated partition/window — no process conflicts). Previously the
 * manager was hidden to free ~45MB of RAM; today this is irrelevant on
 * machines with ≥4GB and prevented multi-account use. In Minimal Mode (<2GB RAM)
 * the old behavior (hide) is kept due to memory constraints.
 *
 * Flow: Play → game window opens (isolated) → manager stays visible →
 * user can open N accounts. Closing the manager (X) with games running only
 * hides it; it returns when the last game closes.
 */
function launchGameForProfile(profileId) {
  if (!uiManager) {
    uiManager = require('./ui/controller');
    if (!uiManager.getManagerWindow()) uiManager.createManagerWindow();
  }
  profileManager.launch(
    profileId,
    function onOpened() {
      activeGameWindows++;
      // Minimal Mode (PC <2GB): hides the manager to free RAM (legacy behavior).
      // Otherwise: manager stays visible → simultaneous multi-account enabled.
      if (memoryGuard.isMinimal() && uiManager) {
        uiManager.hideManager();
        logger.info('Manager hidden (Minimal Mode) — RAM freed for game');
      } else {
        logger.info('Game opened — manager visible (multi-account available)');
      }
    },
    function onClosed() {
      activeGameWindows = Math.max(0, activeGameWindows - 1);
      if (activeGameWindows === 0 && uiManager) {
        // Last game closed: ensures the manager is visible (in case the
        // user hid it manually via X during the game).
        uiManager.showManager();
        logger.info('Game closed — manager restored');
      }
    }
  );
}

function showManager() {
  if (!uiManager) {
    uiManager = require('./ui/controller');
    if (!uiManager.getManagerWindow()) uiManager.createManagerWindow();
    return;
  }
  uiManager.showManager();
}

// ═══════════════════════════════════════════════════════════════════════════
// APP EVENTS
// ═══════════════════════════════════════════════════════════════════════════

app.on('second-instance', function () {
  showManager();
});

// ═══════════════════════════════════════════════════════════════════════════
// ONBOARDING (Setup Window) — first run
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Shows the initial setup screen (500x400, non-resizable).
 * On save, updates config.firstBoot=false + language + advancedMode.
 * @param {Function} onDone - callback when setup is completed
 */
function showSetupWindow(onDone) {
  if (setupWindow && !setupWindow.isDestroyed()) {
    setupWindow.focus();
    return;
  }

  const { BrowserWindow } = require('electron');
  const path = require('path');

  setupWindow = new BrowserWindow({
    width: 500,
    height: 400,
    minWidth: 500,
    minHeight: 400,
    maxWidth: 500,
    maxHeight: 400,
    resizable: false,
    maximizable: false,
    fullscreenable: false,
    useContentSize: true, // exact HTML geometry vs OS title bars
    backgroundColor: '#0a0a0f',
    icon: path.join(__dirname, '..', 'assets', 'icon.png'),
    title: 'Shinobi Launcher — Setup',
    show: false,
    autoHideMenuBar: true,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      backgroundThrottling: false
    }
  });

  // Passes current language via query string (setup.html now in ui/setup/)
  const setupUrl =
    'file://' +
    path.join(__dirname, 'ui', 'setup', 'setup.html') +
    '?lang=' +
    (config.language || 'pt');
  setupWindow.loadURL(setupUrl);

  setupWindow.once('ready-to-show', function () {
    setupWindow.show();
    logger.info('Setup window shown (firstBoot)');
  });

  // Intercepts "close" — setup.html signals via document.title '__SETUP_DONE__{json}'
  setupWindow.on('page-title-updated', function (e, title) {
    if (typeof title === 'string' && title.indexOf('__SETUP_DONE__') === 0) {
      e.preventDefault();
      try {
        const jsonStr = title.slice('__SETUP_DONE__'.length);
        const result = JSON.parse(jsonStr);
        logger.info(
          'Setup complete: lang=' +
            result.language +
            ' region=' +
            (result.region || 'br') +
            ' advanced=' +
            result.advancedMode
        );

        // Apply settings
        config.firstBoot = false;
        config.language = result.language || 'pt';
        config.region = result.region || 'br'; // region selector no setup
        config.advancedMode = result.advancedMode === true;

        // Sync i18n
        i18n.setLanguage(config.language);

        // Persists
        _persistConfig();

        // Recreate mms.cfg with Advanced Light Mode if enabled
        try {
          const { createMmsCfg } = require('./flash/mms');
          createMmsCfg(config.hardwareProfile, { advancedMode: config.advancedMode });
        } catch (_) {
          /* ignore */
        }

        // Closes setup and calls callback
        setupWindow.destroy();
        setupWindow = null;
        if (onDone) onDone();
      } catch (err) {
        logger.error('Failed to process setup result: ' + err.message);
      }
    }
  });

  // If user closes without saving (X), cancel and reopen next time
  setupWindow.on('closed', function () {
    setupWindow = null;
    // If firstBoot is still true (didn't save), keep for next time
    if (config.firstBoot !== false) {
      logger.warn('Setup closed without completing — firstBoot preserved for next launch');
      // Don't call onDone → app doesn't continue, closes
      app.quit();
    }
  });
}

app.on('ready', function () {
  // Flash PPAPI is bundled in the repo (flash/libpepflashplayer.so | pepflashplayer.dll).
  // If not accessible, the installation is corrupted — there is no download fallback.
  if (!flashPath) {
    _showFlashMissingError();
    return;
  }

  // Subsystems
  profileStore.load();

  // EventTimers with full profiles (respects notificationsEnabled per profile)
  eventTimers.startWithProfiles(profileStore.getAll());

  // NO TRAY — app exits when all windows close.

  // ── ONBOARDING — if firstBoot, show setup before manager ──
  if (config.firstBoot !== false) {
    logger.info('First run detected — opening setup window');
    showSetupWindow(function onSetupDone() {
      _initManagerAndLaunch();
    });
    return;
  }

  _initManagerAndLaunch();
});

/**
 * Flash PPAPI missing = corrupted installation.
 * The binary is committed in the repo (flash/); no on-demand download.
 * Shows a dialog and exits — user must reinstall the launcher.
 */
function _showFlashMissingError() {
  logger.error('Flash PPAPI not found — corrupted installation');
  dialog.showMessageBoxSync({
    type: 'error',
    title: 'Flash not found',
    message: 'The Flash PPAPI plugin was not found.',
    detail:
      'The Shinobi Launcher installation appears corrupted — the Flash binary ' +
      'comes bundled in the repository with no automatic download.\n\n' +
      'Reinstall the launcher by downloading the latest version from GitHub.\n' +
      'Flash is required to run Naruto Online.',
    buttons: ['Exit']
  });
  app.exit(1);
}

/**
 * Initializes UI Manager + banner (separate to call after setup).
 */
function _initManagerAndLaunch() {
  // Recreate mms.cfg with Advanced Light Mode if enabled in config
  try {
    const { createMmsCfg } = require('./flash/mms');
    createMmsCfg(config.hardwareProfile, { advancedMode: config.advancedMode === true });
  } catch (_) {
    /* ignore */
  }

  // UI Manager — skip in Minimal Mode (manager-only saves 45MB on PCs <2GB)
  uiManager = require('./ui/controller');
  uiManager.registerIpcHandlers({
    launchProfile: launchGameForProfile,
    closeProfile: profileManager.close, // close game window by profile ID
    getEvents: function (region) {
      return eventTimers.getUpcoming(region || 'br');
    },
    setMuted: function (m) {
      eventTimers.setMuted(m);
      _persistConfig();
    },
    getVault: function (profileId) {
      return vault.getCredentials(profileId);
    },
    setVault: function (profileId, user, pass) {
      return vault.setCredentials(profileId, user, pass);
    },
    removeVault: function (profileId) {
      return vault.removeCredentials(profileId);
    },
    hasVault: function (profileId) {
      return vault.hasCredentials(profileId);
    },
    isLowSpecMode: function () {
      return memoryGuard.isLowSpecMode();
    },
    isMinimal: function () {
      return memoryGuard.isMinimal();
    },
    toggleLowSpec: function () {
      memoryGuard.setForceLowSpec(!memoryGuard.isLowSpecMode());
      partition.setLowSpecMode(memoryGuard.isLowSpecMode());
      _persistConfig();
      return memoryGuard.isLowSpecMode();
    }
  });

  // ── Optimization IPC handlers (GPU + CPU + presets) ──
  // gpuDetector is already required at top-level (for getEnvVars before ready)
  const cpuOptimizer = require('./app/CpuOptimizer');
  const { listForUI, getDefaultPreset } = require('./config/optimization');

  ipcMain.handle('optimization:get-status', function () {
    const gpu = gpuDetector.detect();
    const cpu = cpuOptimizer.getStats();
    const snap = flags.getAppliedSnapshot();
    return {
      preset: config.optimizationPreset || getDefaultPreset(),
      presets: listForUI(),
      // expose advancedMode (Modo PC Fraco) so the UI toggle reflects persisted state.
      advancedMode: config.advancedMode === true,
      // expose cpuRender (Force CPU rendering) — maps to hardwareProfile='cpu'.
      cpuRender: config.hardwareProfile === 'cpu',
      gpu: {
        vendor: gpu.vendor,
        description: gpu.description,
        isPrime: gpu.isPrime,
        hasNvidia: gpu.hasNvidia,
        hasAmd: gpu.hasAmd,
        hasIntel: gpu.hasIntel,
        allGpus: gpu.allGpus.map(function (g) {
          return { vendor: g.vendor, description: g.description };
        })
      },
      cpu: {
        totalCores: cpu.topology.totalCores,
        pCores: cpu.topology.pCores.length,
        eCores: cpu.topology.eCores.length,
        isHybrid: cpu.topology.isHybrid,
        appliedPids: cpu.appliedPids,
        platform: cpu.platform
      },
      applied: snap,
      systemRamGb: flags.SYSTEM_RAM_GB,
      isLowSpec: flags.IS_LOW_SPEC,
      isWayland: flags.IS_WAYLAND
    };
  });

  // PRESETS/listForUI are kept for backwards compat with optimization:get-status response.

  // Toggle Modo PC Fraco (advancedMode / Flash low quality).
  // Re-creates mms.cfg immediately so the change takes effect on next game launch
  // (no launcher restart needed — only the Flash plugin reads mms.cfg at load).
  ipcMain.handle('optimization:set-lowpc', function (_e, enabled) {
    const newState = enabled === true;
    const previous = config.advancedMode === true;
    if (previous === newState) {
      return { ok: true, previous: previous, current: newState, changed: false };
    }
    config.advancedMode = newState;
    _persistConfig();
    try {
      const { createMmsCfg } = require('./flash/mms');
      createMmsCfg(config.hardwareProfile, { advancedMode: newState });
    } catch (err) {
      logger.error('Failed to recreate mms.cfg (lowpc toggle): ' + err.message);
    }
    logger.info('Low-end PC mode (advancedMode): ' + (newState ? 'ON' : 'OFF'));
    return {
      ok: true,
      previous: previous,
      current: newState,
      changed: true
    };
  });

  // Toggle Force CPU rendering (hardwareProfile='cpu' / disable-gpu).
  // Persisted to config; flags.js reads hardwareProfile at boot to decide whether
  // to append --disable-gpu + --use-gl=swiftshader. Requires launcher restart —
  // Chromium flags can't be changed at runtime.
  // When OFF, hardwareProfile='modern' (the default — GPU rendering enabled).
  ipcMain.handle('optimization:set-cpu-render', function (_e, enabled) {
    const newState = enabled === true;
    const previous = config.hardwareProfile === 'cpu';
    if (previous === newState) {
      return { ok: true, previous: previous, current: newState, changed: false };
    }
    config.hardwareProfile = newState ? 'cpu' : 'modern';
    _persistConfig();
    logger.info('Force CPU rendering (hardwareProfile): ' + (newState ? 'cpu' : 'modern'));
    return {
      ok: true,
      previous: previous,
      current: newState,
      changed: true
    };
  });

  // Register preload API handlers (game windows use narutoLauncher API)
  const pkg = require('../package.json');
  ipcMain.handle('launcher:get-version', function () {
    return pkg.version || 'unknown';
  });

  uiManager.createManagerWindow(); // always creates (no tray for fallback)

  _logBanner();
  // flashPath is guaranteed non-null here — boot would
  // branch to _provisionFlashAndRelaunch() otherwise. The UI still
  // may show a warning if the version is unexpected, but doesn't block.
}

app.on('before-quit', function () {
  isQuitting = true;
});

// NO TRAY — when all windows close, the app exits.
// (Previously stayed in tray without restore → "try to close and it doesn't")
app.on('window-all-closed', function () {
  app.quit();
});

// ── Child process crash monitoring ──
// These events do NOT close the main app — we only log for diagnostics.
// Each game BrowserWindow already handles 'render-process-gone' independently
// (in game-launcher.js), but GPU/child-process events are global.
app.on('gpu-process-crashed', function (event) {
  const reason = (event && event.reason) || 'unknown';
  const exitCode = (event && event.exitCode) || '?';
  logger.error('⚡ GPU process crashed — reason=' + reason + ' exitCode=' + exitCode);
});

app.on('child-process-gone', function (event, details) {
  logger.warn(
    '⚡ Child process gone — type=' +
      details.type +
      ' reason=' +
      details.reason +
      ' exitCode=' +
      details.exitCode
  );
});

app.on('will-quit', function () {
  try {
    const { restoreMmsCfg } = require('./flash/mms');
    restoreMmsCfg();
  } catch (_) {
    /* ignore */
  }
  eventTimers.stop();
});

// Graceful exit
process.on('SIGTERM', function () {
  isQuitting = true;
  app.quit();
});
process.on('SIGINT', function () {
  isQuitting = true;
  app.quit();
});
process.on('uncaughtException', function (e) {
  logger.error('Uncaught: ' + e.message + '\n' + (e.stack || ''));
  isQuitting = true;
  app.quit();
});
process.on('unhandledRejection', function (reason) {
  logger.error('Unhandled rejection: ' + reason);
});

// ═══════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════

function _persistConfig() {
  try {
    const { saveConfig } = require('./config/settings');
    // Low-spec machines auto-detect lowSpec mode — don't persist the override
    // since it's auto-detected on every boot. Keep user's explicit choice otherwise.
    if (memoryGuard.IS_LOW_SPEC) {
      config.forceLowSpec = undefined;
    } else if (memoryGuard.isLowSpecMode()) {
      config.forceLowSpec = true;
    }
    // else: keep config.forceLowSpec as-is (user's explicit choice)
    config.mutedEvents = eventTimers.isMuted();
    saveConfig(config);
  } catch (e) {
    logger.debug('main: saveConfig failed: ' + e.message);
  }
}

function _logBanner() {
  var pkg = require('../package.json');
  var ver = pkg.version || 'unknown';
  logger.info('═══════════════════════════════════════════');
  logger.info('  🍥 Shinobi Launcher v' + ver);
  logger.info('  🥷 Zero tracking + Diagnostics exporter + Responsive UI');
  logger.info('═══════════════════════════════════════════');
  logger.info('Flash PPAPI: ' + (flashPath ? '✅ ' + flashVersion : '❌'));
  logger.info('Profiles: ' + profileStore.getAll().length + '/' + profileStore.MAX_PROFILES);
  logger.info('Language: ' + i18n.getLanguage());
  logger.info('System RAM: ' + memoryGuard.SYSTEM_RAM_GB + 'GB');
  logger.info(
    'Low-spec mode: ' +
      (memoryGuard.isLowSpecMode() ? 'ON' : 'OFF') +
      ' (threshold ' +
      memoryGuard.getThreshold() +
      'MB)'
  );
  logger.info('Advanced low-spec: ' + (config.advancedMode ? 'ON (Flash low quality)' : 'OFF'));
  logger.info('═══════════════════════════════════════════');
}

module.exports = {
  isQuitting: function () {
    return isQuitting;
  },
  launchGameForProfile: launchGameForProfile
};
